units:
    kcs: 16.6 # Key Cap Size (of a square choc v1 keycap)
    cos: 14 # Cut Out Size, switch insert footprint in fr4
    cx: 18
    cy: 17
    vertical_underglow_shift: -10 # How much to shift underglow leds tied to keys

points:
  key:
    padding: kcs + 1.4
    spread: kcs + 1.4
  zones:
    matrix:
      key:
        tags:
          - switch
      rows:
        bonus:
        bottom:
        home:
        top:
      columns:
        outer:
          rows.bonus.skip: true
        pinky:
          rows.bonus.skip: true
          key.stagger: 4
        ring:
          key.stagger: 14
        middle:
          rows.bonus.skip: true
          key.stagger: 4
        index:
          rows.bonus.skip: true
          key.stagger: -5
        inner:
          rows.bonus.skip: true
          key.stagger: -4
        bonus:
          rows.bonus.skip: true
          key:
            skip: true
            stagger: -2.8
          rows:
            bottom.skip: false
    thumb:
      key:
        tags:
          - switch
      rows:
        thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-28, -18]

      columns:
        inner:
        close:
        home:
          key.spread: 18
          key.splay: -15
          key.origin: [-9, -7]

        outer:
          key.spread: 18
          key.splay: -15
          key.origin: [-9, -7]
    underglow_led_1:
      key:
        tags:
          - underglow
        din: LED
        dout: ULED_1
      anchor:
        - ref: matrix_inner_top
          shift: [0, vertical_underglow_shift]

    underglow_led_2:
      key:
        tags:
          - underglow
        din: ULED_1
        dout: ULED_2
      anchor:
        - ref: matrix_middle_top
          shift: [0, vertical_underglow_shift]

    underglow_led_3:
      key:
        tags:
          - underglow
        din: ULED_2
        dout: ULED_3
      anchor:
        - ref: matrix_pinky_top
          shift: [0, vertical_underglow_shift]

    underglow_led_4:
      key:
        tags:
          - underglow
        din: ULED_3
        dout: ULED_4
      anchor:
        - ref: matrix_pinky_home
          shift: [0, vertical_underglow_shift]

    underglow_led_5:
      key:
        tags:
          - underglow
        din: ULED_4
        dout: ULED_5
      anchor:
        - ref: matrix_middle_bottom
          shift: [0, vertical_underglow_shift]

    underglow_led_6:
      key:
        tags:
          - underglow
        din: ULED_5
        dout: ULED_6
      anchor:
        - ref: matrix_inner_bottom
          shift: [0, vertical_underglow_shift]

outlines:
  cutouts:
    - what: rectangle
      where: switch
      bound: false
      size: cos
  keycaps:
    - what: rectangle
      where: switch
      bound: false
      size: 16.6
  controller:
    - what: rectangle
      size: [17.78, 33]
      adjust:
        ref: matrix_inner_top
        shift: [kcs + 2, -8.2]
  pcb:
    - what: polygon
      operation: stack
      fillet: 1.5
      points:
        - ref: matrix_outer_bottom
          shift: [50, -0.6kcs]

        - ref: matrix_outer_bottom
          shift: [-0.6kcs, -0.6kcs]

        - ref: matrix_outer_top
          shift: [-0.6kcs, 0.6kcs]

        - ref: matrix_outer_top
          shift: [8, 0.6kcs]

        - ref: matrix_pinky_top
          shift: [-10, 0.6kcs]

        - ref: matrix_pinky_top
          shift: [8, 0.6kcs]

        - ref: matrix_ring_top
          shift: [-10, 0.6kcs]

        - ref: matrix_ring_top
          shift: [8, 0.6kcs]

        - ref: matrix_middle_top
          shift: [-10, 0.6kcs]

        - ref: matrix_middle_top
          shift: [10, 0.6kcs]

        - ref: matrix_index_top
          shift: [-8, 0.6kcs]

        - ref: matrix_index_top
          shift: [10, 0.6kcs]

        - ref: matrix_inner_top
          shift: [-8, 0.6kcs]

        - ref: matrix_inner_top
          shift: [1.8kcs, 0.6kcs]

        - ref: matrix_inner_top
          shift: [1.8kcs, -3kcs]

        - ref: thumb_outer_thumb
          shift: [0.6kcs, 0.6kcs]
        - ref: thumb_outer_thumb
          shift: [0.6kcs, -0.6kcs]
        - ref: thumb_home_thumb
          shift: [0.5kcs, -0.6kcs]
        - ref: thumb_home_thumb
          shift: [-0.5kcs, -0.6kcs]
        - ref: thumb_inner_thumb
          shift: [-0.6kcs, -0.6kcs]
  combo:
    - operation: stack
      name: pcb
    - operation: stack
      name: cutouts
    - operation: stack
      name: keycaps
    - operation: stack
      name: controller

pcbs.left:
  outlines:
    main:
      outline: pcb
  footprints:
    switches:
      what: choc
      where: switch
      params:
        reverse: false
        keycaps: true
        hotswap: true
        from: "{{col_net}}"
        to: "{{colrow}}"
      adjust:
        rotate: 180
    diodes:
      what: diode_tht_sod123
      where: switch
      params:
        from: "{{colrowt}}"
        to: "{{row_net}}"
      adjust:
        shift: [8, 4.4]
        rotate: 90
    backlight_leds:
        what: led_sk6812mini-e
        where: switch
        params:
          P1: VCC
          P2: "{{key.led_next}}" #DOUT
          P3: GND
          P4: "{{key.led_prev}}" #DIN
          reversible: false
          reverse_mount: true
        adjust:
          shift: [0, 4.7]
          rotate: 0
    underglow_leds:
      what: ws2812b
      where: [underglow]
      params:
        side: B
        VCC: "{{VCC}}"
        din: "{{din}}"
        dout: "{{dout}}"
    controller:
      what: nicenano
      adjust:
        ref: matrix_inner_top
        shift: [kcs + 3, -8.2]
        rotate: -90
    bat_con:
      what: battery_connector_jst_ph_2
    pwr_sw:
      what: power_switch_smd_side
    rst_bt:
      what: reset_switch_smd_side
