units:
  kcs: 16.6 # Key Cap Size (of a square choc v1 keycap)
  cos: 14 # Cut Out Size, switch insert footprint in fr4
  border_offset: 0.5kcs
  cx: 18
  cy: 17
  vertical_underglow_shift: -10 # How much to shift underglow leds tied to keys

points:
  key:
    padding: kcs + 1.4
    spread: kcs + 1.4
  zones:
    matrix:
      anchor:
        shift: [170, -190] # position on kicad sheet
      key:
        tags:
          - switch
      rows:
        bonus:
          row_net: P104
        bottom:
          row_net: P011
        home:
          row_net: P100
        top:
          row_net: P024
      columns:
        outer:
          rows:
            bonus.skip: true
          key:
            column_net: P031
        pinky:
          rows:
            bonus.skip: true
          key:
            stagger: 4
            column_net: P029
        ring:
          key:
            stagger: 10.5
            column_net: P002
        middle:
          rows:
            bonus.skip: true
          key:
            stagger: 4
            column_net: P115
        index:
          rows:
            bonus.skip: true
          key:
            stagger: -5
            column_net: P113
        inner:
          rows:
            bonus.skip: true
          key:
            stagger: -2
            column_net: P111
    thumbfan:
      rows:
        thumb:
          row_net: P104
      anchor:
        ref: matrix_inner_bottom
        shift: [-36, -18]
      columns:
        inner:
          key:
            column_net: P115
        close:
          key:
            column_net: P113
        home:
          key:
            spread: 18
            splay: -15
            origin: [-9, -7]
            column_net: P111
        outer:
          key:
            spread: 18
            splay: -15
            origin: [-9, -7]
            column_net: P010

    controller:
      anchor:
        - ref: matrix_inner_top
          shift: [kcs + 2.2, -9.8]
    nice_view:
      anchor:
        - ref: controller
          shift: [0, -19]
    pwr_sw:
      anchor:
        - ref: controller
          shift: [7.6, -25]
    rst_button:
      anchor:
        - ref: controller
          shift: [7.4, -35]
    bat_con:
      anchor:
        - ref: controller
          shift: [-6, -33]
    logo:
      anchor:
        - ref: controller
          shift: [0, -26]

    standoff_hole_1:
      anchor:
        - ref: matrix_inner_top
          shift: [-9, -9]
    standoff_hole_2:
      anchor:
        - ref: matrix_outer_home
          shift: [9, 9]
    standoff_hole_3:
      anchor:
        - ref: matrix_outer_bottom
          shift: [9, 9]
    standoff_hole_4:
      anchor:
        - ref: matrix_inner_bottom
          shift: [-9, -9]
    standoff_hole_5:
      anchor:
        - ref: thumbfan_outer_thumb
          shift: [-10.45, 4]


    mounting_hole_6:
      anchor:
        - ref: nice_view
          shift: [-7, -18]
    mounting_hole_7:
      anchor:
        - ref: nice_view
          shift: [7, -25]

  mirror:
    ref: matrix_inner_home
    distance: -100

outlines:
  cutouts:
    - what: rectangle
      where: switch
      bound: false
      size: cos
  keycaps:
    - what: rectangle
      where: switch
      bound: false
      size: kcs
  controller:
    - what: rectangle
      where: nice_nano
      size: [17.78, 33]
  pcb_left:
    - what: polygon
      operation: stack
      fillet: 0.7
      points:
          # bottom left corner
        - ref: matrix_outer_bottom
          shift: [-(border_offset + 1.35), -border_offset]
        - ref: matrix_outer_top
          shift: [-(border_offset + 1.35), border_offset]
        - ref: matrix_outer_top
          shift: [border_offset + 1.4, border_offset]
        - ref: matrix_pinky_top
          shift: [-border_offset, border_offset]
        - ref: matrix_pinky_top
          shift: [border_offset + 1.4, border_offset]
        - ref: matrix_ring_top
          shift: [-border_offset, border_offset]
        - ref: matrix_ring_top
          shift: [border_offset + 1.4, border_offset]
        - ref: matrix_middle_top
          shift: [-border_offset, border_offset]
        - ref: matrix_middle_top
          shift: [border_offset, border_offset]
        - ref: matrix_index_top
          shift: [-(border_offset + 1.4), border_offset]
        - ref: matrix_index_top
          shift: [border_offset, border_offset]
        - ref: matrix_inner_top
          shift: [-(border_offset + 1.4), border_offset]
          # top right corner
        - ref: matrix_inner_top
          shift: [border_offset + 19.8, border_offset]
        - ref: matrix_inner_top
          shift: [border_offset + 19.8, -3kcs]
        - ref: thumbfan_outer_thumb
          shift: [border_offset, border_offset]
          # bottom right corner
        - ref: thumbfan_outer_thumb
          shift: [border_offset, -border_offset]
        - ref: thumbfan_home_thumb
          shift: [border_offset + 0.525, -border_offset]
        - ref: thumbfan_close_thumb
          shift: [border_offset + 0.525, -border_offset]
        - ref: thumbfan_inner_thumb
          shift: [-border_offset, -border_offset]
  pcb_right:
    - what: polygon
      operation: stack
      fillet: 0.7
      points:
        # bottom left corner
        - ref: mirror_matrix_outer_bottom
          shift: [-(border_offset + 1.35), -border_offset]
        - ref: mirror_matrix_outer_top
          shift: [-(border_offset + 1.35), border_offset]
        - ref: mirror_matrix_outer_top
          shift: [border_offset + 1.4, border_offset]
        - ref: mirror_matrix_pinky_top
          shift: [-border_offset, border_offset]
        - ref: mirror_matrix_pinky_top
          shift: [border_offset + 1.4, border_offset]
        - ref: mirror_matrix_ring_top
          shift: [-border_offset, border_offset]
        - ref: mirror_matrix_ring_top
          shift: [border_offset + 1.4, border_offset]
        - ref: mirror_matrix_middle_top
          shift: [-border_offset, border_offset]
        - ref: mirror_matrix_middle_top
          shift: [border_offset, border_offset]
        - ref: mirror_matrix_index_top
          shift: [-(border_offset + 1.4), border_offset]
        - ref: mirror_matrix_index_top
          shift: [border_offset, border_offset]
        - ref: mirror_matrix_inner_top
          shift: [-(border_offset + 1.4), border_offset]
          # top right corner
        - ref: mirror_matrix_inner_top
          shift: [border_offset + 19.8, border_offset]
        - ref: mirror_matrix_inner_top
          shift: [border_offset + 19.8, -3kcs]
        - ref: mirror_thumbfan_outer_thumb
          shift: [border_offset, border_offset]
          # bottom right corner
        - ref: mirror_thumbfan_outer_thumb
          shift: [border_offset, -border_offset]
        - ref: mirror_thumbfan_home_thumb
          shift: [border_offset + 0.525, -border_offset]
        - ref: mirror_thumbfan_close_thumb
          shift: [border_offset + 0.525, -border_offset]
        - ref: mirror_thumbfan_inner_thumb
          shift: [-border_offset, -border_offset]
  combo:
    - operation: stack
      name: pcb_left
    - operation: stack
      name: cutouts
    - operation: stack
      name: keycaps
    - operation: stack
      name: controller

pcbs:
  left:
    outlines:
      main:
        outline: pcb_left
    footprints:
      switches:
        what: choc_lio
        where: /(^matrix_.*)|(^thumbfan_.*)/
        params:
          reverse: false
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diodes:
        what: diode_tht_sod123
        where: /(^matrix_(?!(?:ring_top.*)).*)|(^thumbfan_.*)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8.29, 0.4]
          rotate: -90
      diode_conflict:
        what: diode_tht_sod123
        where: matrix_ring_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.4, 0.35]
          rotate: -90
      controller:
        what: nicenano
        where: controller
        adjust:
          rotate: -90
      nice_view:
        what: niceview
        where: nice_view
        adjust:
          rotate: 90
        params:
          CS: P022
          SCK: P020
          MOSI: P017
      pwr_sw:
        what: power_switch_smd_side
        where: pwr_sw
      rst_button:
        what: reset_switch_smd_side
        where: rst_button
        params:
          include_bosses: true
        adjust:
          rotate: -90
      bat_con:
        what: battery_connector_jst_ph_2
        where: bat_con
        adjust:
          rotate: 180
      mounting_holes:
        what: mounting_hole_plated
        where: /^mounting_hole_.*/
      standoff_holes:
        what: mounting_hole_npth
        where: /^standoff_hole_.*/
        params:
          hole_size: 3
          hole_drill: 3
      logo:
        what: lio_logo
        where: logo
        params:
          side: "B"

  right:
    outlines:
      main:
        outline: pcb_right
    footprints:
      switches:
        what: choc_lio
        where: /(^mirror_matrix_.*)|(^mirror_thumbfan_(?!(?:outer_thumb.*)).*)/
        params:
          reverse: false
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      outer_tumb_switch:
        what: choc_lio
        where: mirror_thumbfan_outer_thumb
        params:
          reverse: false
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -90
      diodes:
        what: diode_tht_sod123
        where: /(^mirror_matrix_.*)|(^mirror_thumbfan_(?!(?:outer_thumb.*)).*)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8.3, 0.4]
          rotate: 90
      outer_thumb_diode:
        what: diode_tht_sod123
        where: mirror_thumbfan_outer_thumb
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-0.4, 8.29]
          rotate: 180
      controller:
        what: nicenano
        where: mirror_controller
        adjust:
          rotate: 90
      nice_view:
        what: niceview
        where: mirror_nice_view
        adjust:
          rotate: -90
        params:
          CS: P022
          SCK: P020
          MOSI: P017
      pwr_sw:
        what: power_switch_smd_side
        where: mirror_pwr_sw
        adjust:
          rotate: 180
      rst_button:
        what: reset_switch_smd_side
        where: mirror_rst_button
        params:
          include_bosses: true
        adjust:
          rotate: -90
      bat_con:
        what: battery_connector_jst_ph_2
        where: mirror_bat_con
        adjust:
          rotate: 180
      mounting_holes:
        what: mounting_hole_plated
        where: /^mirror_mounting_hole_.*/
      standoff_holes:
        what: mounting_hole_npth
        where: /^mirror_standoff_hole_.*/
        params:
          hole_size: 3
          hole_drill: 3
      logo:
        what: lio_logo_mirror
        where: mirror_logo
        params:
          side: "B"
        adjust:
          rotate: 180
